improv.nexus ************ new improv server session 2023-07-20 23:47:29 ************
improv.nexus StoreInterface started successfully at location: /tmp/4e4578f3-e427-406a-94cd-e75d1735b783
asyncio Using selector: EpollSelector
improv.nexus Create new store object
improv.store Successfully connected to store at locations /tmp/4e4578f3-e427-406a-94cd-e75d1735b783 
improv.store Unknown error: 'NoneType' object has no attribute 'subscribe'
Traceback (most recent call last):
  File "/home/chrisunix/improv/improv/store.py", line 290, in subscribe
    self.client.subscribe()
AttributeError: 'NoneType' object has no attribute 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisunix/anaconda3/envs/improv/bin/improv", line 8, in <module>
    sys.exit(default_invocation())
  File "/home/chrisunix/improv/improv/cli.py", line 202, in default_invocation
    args.func(args)
  File "/home/chrisunix/improv/improv/cli.py", line 235, in run_server
    control_port, output_port = server.createNexus(
  File "/home/chrisunix/improv/improv/nexus.py", line 71, in createNexus
    self.store.subscribe()
  File "/home/chrisunix/improv/improv/store.py", line 293, in subscribe
    raise Exception
Exception
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7fb354b8b0a0>
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.REP) at 0x7fb354b8b2e0>
/home/chrisunix/anaconda3/envs/improv/lib/python3.9/subprocess.py:1048: ResourceWarning: subprocess 625 is still running
  _warn("subprocess %s is still running" % self.pid,
improv.nexus ************ new improv server session 2023-07-20 23:47:48 ************
improv.nexus StoreInterface started successfully at location: /tmp/a90fea46-4e25-427f-8c72-a04edb656e79
asyncio Using selector: EpollSelector
improv.nexus Create new store object
improv.store Successfully connected to store at locations /tmp/a90fea46-4e25-427f-8c72-a04edb656e79 
improv.store Unknown error: 'NoneType' object has no attribute 'subscribe'
Traceback (most recent call last):
  File "/home/chrisunix/improv/improv/store.py", line 290, in subscribe
    self.client.subscribe()
AttributeError: 'NoneType' object has no attribute 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisunix/anaconda3/envs/improv/bin/improv", line 8, in <module>
    sys.exit(default_invocation())
  File "/home/chrisunix/improv/improv/cli.py", line 202, in default_invocation
    args.func(args)
  File "/home/chrisunix/improv/improv/cli.py", line 235, in run_server
    control_port, output_port = server.createNexus(
  File "/home/chrisunix/improv/improv/nexus.py", line 71, in createNexus
    self.store.subscribe()
  File "/home/chrisunix/improv/improv/store.py", line 293, in subscribe
    raise Exception
Exception
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7fc7ed0db100>
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.REP) at 0x7fc7ed0db340>
/home/chrisunix/anaconda3/envs/improv/lib/python3.9/subprocess.py:1048: ResourceWarning: subprocess 637 is still running
  _warn("subprocess %s is still running" % self.pid,
improv.nexus ************ new improv server session 2023-07-20 23:56:26 ************
improv.nexus StoreInterface started successfully at location: /tmp/4d2ac662-be00-4fb3-b788-8a9d607939b4
asyncio Using selector: EpollSelector
improv.nexus Create new store object
improv.store Successfully connected to store at locations /tmp/4d2ac662-be00-4fb3-b788-8a9d607939b4 
improv.store Unknown error: 'NoneType' object has no attribute 'subscribe'
Traceback (most recent call last):
  File "/home/chrisunix/improv/improv/store.py", line 290, in subscribe
    self.client.subscribe()
AttributeError: 'NoneType' object has no attribute 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisunix/anaconda3/envs/improv/bin/improv", line 8, in <module>
    sys.exit(default_invocation())
  File "/home/chrisunix/improv/improv/cli.py", line 202, in default_invocation
    args.func(args)
  File "/home/chrisunix/improv/improv/cli.py", line 235, in run_server
    control_port, output_port = server.createNexus(
  File "/home/chrisunix/improv/improv/nexus.py", line 71, in createNexus
    self.store.subscribe()
  File "/home/chrisunix/improv/improv/store.py", line 293, in subscribe
    raise Exception
Exception
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7fdec0b1c100>
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.REP) at 0x7fdec0b1c340>
/home/chrisunix/anaconda3/envs/improv/lib/python3.9/subprocess.py:1048: ResourceWarning: subprocess 1165 is still running
  _warn("subprocess %s is still running" % self.pid,
improv.nexus ************ new improv server session 2023-07-20 23:56:44 ************
improv.nexus StoreInterface started successfully at location: /tmp/339b13f6-5853-4faf-b5e7-a2df8e9acd2d
asyncio Using selector: EpollSelector
improv.nexus Create new store object
improv.store Successfully connected to store at locations /tmp/339b13f6-5853-4faf-b5e7-a2df8e9acd2d 
improv.store Unknown error: 'NoneType' object has no attribute 'subscribe'
Traceback (most recent call last):
  File "/home/chrisunix/improv/improv/store.py", line 290, in subscribe
    self.client.subscribe()
AttributeError: 'NoneType' object has no attribute 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisunix/anaconda3/envs/improv/bin/improv", line 8, in <module>
    sys.exit(default_invocation())
  File "/home/chrisunix/improv/improv/cli.py", line 202, in default_invocation
    args.func(args)
  File "/home/chrisunix/improv/improv/cli.py", line 235, in run_server
    control_port, output_port = server.createNexus(
  File "/home/chrisunix/improv/improv/nexus.py", line 71, in createNexus
    self.store.subscribe()
  File "/home/chrisunix/improv/improv/store.py", line 293, in subscribe
    raise Exception
Exception
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7f1c2302b100>
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.REP) at 0x7f1c2302b340>
/home/chrisunix/anaconda3/envs/improv/lib/python3.9/subprocess.py:1048: ResourceWarning: subprocess 1177 is still running
  _warn("subprocess %s is still running" % self.pid,
improv.nexus ************ new improv server session 2023-07-21 00:04:40 ************
improv.nexus StoreInterface started successfully at location: /tmp/e07e3bef-3366-44e4-a592-2f3f9dee8189
asyncio Using selector: EpollSelector
improv.nexus Create new store object
improv.store Successfully connected to store at locations /tmp/e07e3bef-3366-44e4-a592-2f3f9dee8189 
improv.store Unknown error: 'NoneType' object has no attribute 'subscribe'
Traceback (most recent call last):
  File "/home/chrisunix/improv/improv/store.py", line 290, in subscribe
    self.client.subscribe()
AttributeError: 'NoneType' object has no attribute 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisunix/anaconda3/envs/improv/bin/improv", line 8, in <module>
    sys.exit(default_invocation())
  File "/home/chrisunix/improv/improv/cli.py", line 202, in default_invocation
    args.func(args)
  File "/home/chrisunix/improv/improv/cli.py", line 235, in run_server
    control_port, output_port = server.createNexus(
  File "/home/chrisunix/improv/improv/nexus.py", line 71, in createNexus
    self.store.subscribe()
  File "/home/chrisunix/improv/improv/store.py", line 293, in subscribe
    raise Exception
Exception
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7f0d1cd6c100>
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.REP) at 0x7f0d1cd6c340>
/home/chrisunix/anaconda3/envs/improv/lib/python3.9/subprocess.py:1048: ResourceWarning: subprocess 1689 is still running
  _warn("subprocess %s is still running" % self.pid,
improv.nexus ************ new improv server session 2023-07-21 00:04:58 ************
improv.nexus StoreInterface started successfully at location: /tmp/e7e9fa77-09c7-49e3-809f-2bb8885f46ba
asyncio Using selector: EpollSelector
improv.nexus Create new store object
improv.store Successfully connected to store at locations /tmp/e7e9fa77-09c7-49e3-809f-2bb8885f46ba 
improv.store Unknown error: 'NoneType' object has no attribute 'subscribe'
Traceback (most recent call last):
  File "/home/chrisunix/improv/improv/store.py", line 290, in subscribe
    self.client.subscribe()
AttributeError: 'NoneType' object has no attribute 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisunix/anaconda3/envs/improv/bin/improv", line 8, in <module>
    sys.exit(default_invocation())
  File "/home/chrisunix/improv/improv/cli.py", line 202, in default_invocation
    args.func(args)
  File "/home/chrisunix/improv/improv/cli.py", line 235, in run_server
    control_port, output_port = server.createNexus(
  File "/home/chrisunix/improv/improv/nexus.py", line 71, in createNexus
    self.store.subscribe()
  File "/home/chrisunix/improv/improv/store.py", line 293, in subscribe
    raise Exception
Exception
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7f88c567b100>
sys:1: ResourceWarning: unclosed socket <zmq.asyncio.Socket(zmq.REP) at 0x7f88c567b340>
/home/chrisunix/anaconda3/envs/improv/lib/python3.9/subprocess.py:1048: ResourceWarning: subprocess 1701 is still running
  _warn("subprocess %s is still running" % self.pid,
